# Generated by Django 3.0.3 on 2020-04-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAD_app', '0002_auto_20200421_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='password',
            field=models.CharField(default=12345, max_length=100),
        ),
    ]
