# Generated by Django 3.0.3 on 2020-04-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAD_app', '0003_user_info_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='email',
        ),
        migrations.AddField(
            model_name='user_info',
            name='username',
            field=models.CharField(default='none', max_length=100, unique=True),
        ),
    ]
