# Generated by Django 3.0.3 on 2020-04-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAD_app', '0004_auto_20200421_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='username',
        ),
        migrations.AddField(
            model_name='user_info',
            name='email',
            field=models.EmailField(max_length=264, null=True, unique=True),
        ),
    ]
