# Generated by Django 3.0.3 on 2020-04-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAD_app', '0005_auto_20200421_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
