# Generated by Django 3.0.3 on 2020-04-21 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EAD_app', '0006_user_info_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='username',
        ),
        migrations.AddField(
            model_name='user_info',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
