# Generated by Django 3.0.3 on 2020-04-22 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EAD_app', '0014_auto_20200422_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='role',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_by', models.CharField(choices=[('nss', 'Nss'), ('ncc', 'NCC'), ('project', 'Project')], max_length=20)),
                ('rew_by_oi', models.BooleanField(default=False)),
                ('rew_by_hod', models.BooleanField(default=False)),
                ('rew_by_labt', models.BooleanField(default=False)),
                ('app_by_cdgc', models.BooleanField(default=False)),
                ('app_by_oi', models.BooleanField(default=False)),
                ('app_by_da', models.BooleanField(default=False)),
                ('app_by_dsa', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('requested_venue', models.CharField(max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
