# Generated by Django 3.0.3 on 2020-04-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAD_app', '0015_auto_20200422_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='requested_venue',
            field=models.CharField(choices=[('nss', 'Nss'), ('ncc', 'NCC'), ('project', 'Project')], max_length=10),
        ),
    ]
