# Generated by Django 3.0.3 on 2020-04-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAD_app', '0018_auto_20200422_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='description',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
