# Generated by Django 3.0.3 on 2020-04-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAD_app', '0019_user_info_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='associated_club',
            field=models.CharField(choices=[('nss', 'NSS'), ('voyagers', 'Voyagers'), ('saasc', 'SAASC')], max_length=20, null=True),
        ),
    ]
