# Generated by Django 3.0.3 on 2020-04-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAD_app', '0020_venue_associated_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('secretary', 'secretary')], max_length=10),
        ),
    ]
