# Generated by Django 3.0.3 on 2020-04-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAD_app', '0024_auto_20200423_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='requested_venue_secy',
            field=models.CharField(choices=[('l26', 'LH-16'), ('Auditorium', 'Auditorium'), ('Audi With Arena', 'Audi Arena')], max_length=20),
        ),
    ]
