# Generated by Django 3.0.3 on 2020-04-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAD_app', '0025_auto_20200423_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='requested_venue_secy',
            field=models.CharField(blank=True, choices=[('l26', 'LH-16'), ('Auditorium', 'Auditorium'), ('Audi With Arena', 'Audi Arena')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='requested_venue_student',
            field=models.CharField(blank=True, choices=[('303', 'lab-303'), ('306', 'lab-306'), ('307', 'lab-307')], max_length=20, null=True),
        ),
    ]
