# Generated by Django 3.0.3 on 2020-04-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAD_app', '0026_auto_20200423_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
