# Generated by Django 3.0.3 on 2020-04-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAD_app', '0027_auto_20200423_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='app_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venue',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
