# Generated by Django 3.0.3 on 2020-04-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAD_app', '0029_auto_20200424_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='role',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
