# Generated by Django 3.0.3 on 2020-04-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAD_app', '0030_auto_20200424_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='requested_venue_student',
            field=models.CharField(blank=True, choices=[('303', 'lab-303'), ('306', 'lab-306'), ('307', 'lab-307'), ('cl13', 'CL-13'), ('cl14', 'CL-14')], max_length=20, null=True),
        ),
    ]
