# Generated by Django 3.0.3 on 2020-04-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAD_app', '0031_auto_20200424_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='date',
            field=models.DateField(),
        ),
    ]
