# Generated by Django 3.0.3 on 2020-04-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAD_app', '0033_auto_20200424_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='associated_club',
            field=models.CharField(blank=True, choices=[('nss', 'NSS'), ('voyagers', 'Voyagers'), ('saasc', 'SAASC')], max_length=20, null=True),
        ),
    ]
