# Generated by Django 3.0.3 on 2020-04-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAD_app', '0034_auto_20200424_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='considered',
            field=models.BooleanField(default=False),
        ),
    ]
