# Generated by Django 3.0.3 on 2020-04-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EAD_app', '0037_auto_20200424_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='associated_club',
            field=models.CharField(blank=True, choices=[('nss', 'NSS'), ('voyagers', 'Voyagers'), ('saasc', 'SAASC'), ('CSS', 'CSS'), ('IEEE', 'IEEE'), ('robotics', 'robotics'), ('music_club', 'music_club')], max_length=20, null=True),
        ),
    ]
